# Generated by Django 4.2.14 on 2024-07-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='usuario_registro',
        ),
    ]
