# Generated by Django 4.2.15 on 2024-09-08 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colecciones', '0001_initial'),
        ('medical', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.CharField(choices=[('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30')], max_length=5)),
                ('especialidad', models.CharField(max_length=100)),
                ('edad_paciente', models.IntegerField()),
                ('motivo', models.CharField(choices=[('Revision de Examenes', 'Revisión de Exámenes'), ('Cita Medica', 'Cita Médica')], max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colecciones.diagnostico')),
                ('examenes', models.ManyToManyField(blank=True, to='colecciones.examen')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
