# Generated by Django 4.2.15 on 2024-09-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='edad_paciente',
        ),
    ]
